name: ostello_ai_app
description: ""
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  auto_route: ^7.8.3
  cached_network_image: ^3.3.1
  dio: ^5.3.2
  dio_smart_retry: ^5.0.0
  duration: ^3.0.13
  equatable: ^2.0.5
  flash: ^3.0.5+1
  flex_color_scheme: ^7.3.1
  flutter:
    sdk: flutter
  flutter_displaymode: ^0.6.0
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.4.0
  flutter_svg: ^2.0.10+1
  google_fonts: ^6.2.0
  hive_flutter: ^1.1.0
  internet_connection_checker_plus: ^2.0.0
  intl: ^0.18.1
  outline_gradient_button: ^2.0.1+1
  path_provider: ^2.1.1
  platform_info: ^4.0.2
  responsive_framework: ^1.1.1
  shared_preferences: ^2.2.2
  talker_dio_logger: ^2.3.0
  talker_flutter: ^3.2.7
  velocity_x: ^4.1.1

dev_dependencies:
  auto_route_generator: ^7.1.1
  build_runner: ^2.4.6
  custom_lint: ^0.5.1
  flutter_lints: ^2.0.2
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  riverpod_lint: ^2.1.0
  riverpod_test: ^0.1.3
  very_good_analysis: ^5.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
#    - assets/icons/
    - assets/images/
#    - assets/svgs/
#    - assets/fonts/
  fonts:
#    - family: Avenir
#      fonts:
#        - asset: assets/fonts/AvenirLTStd-Book.otf
#        - asset: assets/fonts/AvenirLTStd-Heavy.otf
#        - asset: assets/fonts/AvenirLTStd-Light.otf
#        - asset: assets/fonts/AvenirLTStd-Medium.otf
#        - asset: assets/fonts/AvenirLTStd-Roman.otf
    - family: Metropolis
      fonts:
        - asset: assets/fonts/Metropolis-Regular.otf
        - asset: assets/fonts/Metropolis-Bold.otf
        - asset: assets/fonts/Metropolis-ExtraBold.otf
        - asset: assets/fonts/Metropolis-Medium.otf
        - asset: assets/fonts/Metropolis-SemiBold.otf
        - asset: assets/fonts/Metropolis-Light.otf
        - asset: assets/fonts/Metropolis-Thin.otf
